import { Router } from "https://deno.land/x/oak@v12.6.1/mod.ts";
import { PDFDocument, StandardFonts, rgb } from "https://esm.sh/pdf-lib@1.17.1";
import { supabase } from "../lib/supabase.ts";

const REPORT_VERSION = "v1.3 | Generated by SaveOnLease Engine";

interface PortfolioLease {
  property_name?: string;
  landlord?: string;
  square_feet?: number;
  lease_type?: string;
  renewal_date?: string;
  estimated_exposure?: number;
  diffDays?: number;
  region?: string;
}

interface PortfolioRequest {
  source?: "saved_portfolio";
  leases?: PortfolioLease[];
  totalExposure: number;
  riskBuckets: {
    critical: number;
    watch: number;
    safe: number;
  };
  companyName: string;
  confidential: boolean;
  priorExposure?: number;
}

const router = new Router();

function savedDateDays(value: string | undefined, today: Date): number | null {
  if (!value || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return null;
  const parsed = Date.parse(`${value}T00:00:00Z`);
  if (!Number.isFinite(parsed) || new Date(parsed).toISOString().slice(0, 10) !== value) return null;
  const todayUtc = Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), today.getUTCDate());
  return Math.round((parsed - todayUtc) / 86_400_000);
}

async function generateSavedPortfolioPdf(leases: PortfolioLease[]): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const ink = rgb(0.09, 0.16, 0.25);
  const muted = rgb(0.37, 0.43, 0.51);
  const today = new Date();
  const counts = { due: 0, watch: 0, later: 0, missing: 0 };
  const dated = leases.map((lease) => ({ lease, days: savedDateDays(lease.renewal_date, today) }));
  for (const { days } of dated) {
    if (days === null) counts.missing++;
    else if (days <= 90) counts.due++;
    else if (days <= 180) counts.watch++;
    else counts.later++;
  }

  function ascii(value: unknown): string {
    return String(value ?? "").normalize("NFKD")
      .replace(/[\u2010-\u2015]/g, "-")
      .replace(/[^\x20-\x7e]/g, "?");
  }
  function fitted(value: unknown, maxWidth: number, size: number): string {
    let result = ascii(value);
    while (result && font.widthOfTextAtSize(result, size) > maxWidth) result = result.slice(0, -1);
    return result === ascii(value) ? result : `${result.slice(0, -3)}...`;
  }

  const summary = pdf.addPage([842, 595]);
  summary.drawRectangle({ x: 0, y: 0, width: 842, height: 595, color: rgb(0.97, 0.98, 1) });
  summary.drawRectangle({ x: 0, y: 500, width: 842, height: 95, color: ink });
  summary.drawText("Portfolio board report", { x: 40, y: 550, size: 24, font: bold, color: rgb(1, 1, 1) });
  summary.drawText("Saved lease details and renewal dates", { x: 40, y: 525, size: 11, font, color: rgb(0.78, 0.84, 0.93) });
  summary.drawText(`Generated ${today.toISOString().slice(0, 10)} (UTC)`, { x: 40, y: 475, size: 11, font, color: muted });

  const cards = [
    ["Active leases", leases.length],
    ["Past or within 90 days", counts.due],
    ["91-180 days", counts.watch],
    ["Date not saved", counts.missing],
  ] as const;
  cards.forEach(([label, value], index) => {
    const x = 40 + index * 192;
    summary.drawRectangle({ x, y: 375, width: 177, height: 72, color: rgb(1, 1, 1) });
    summary.drawText(label, { x: x + 12, y: 422, size: 10, font, color: muted });
    summary.drawText(String(value), { x: x + 12, y: 389, size: 25, font: bold, color: ink });
  });
  summary.drawText("Upcoming saved renewal dates", { x: 40, y: 338, size: 15, font: bold, color: ink });
  const upcoming = dated.filter((item) => item.days !== null && item.days >= 0)
    .sort((a, b) => (a.days ?? 0) - (b.days ?? 0)).slice(0, 10);
  if (upcoming.length === 0) {
    summary.drawText("No future renewal dates are saved.", { x: 40, y: 307, size: 11, font, color: muted });
  } else {
    upcoming.forEach(({ lease, days }, index) => {
      const y = 308 - index * 22;
      summary.drawText(fitted(lease.property_name || "Unnamed lease", 490, 10), { x: 40, y, size: 10, font, color: ink });
      summary.drawText(lease.renewal_date || "", { x: 555, y, size: 10, font, color: ink });
      summary.drawText(`${days} days`, { x: 685, y, size: 10, font, color: muted });
    });
  }
  summary.drawText("Dates come from saved portfolio entries. Confirm renewal and notice terms against each lease.",
    { x: 40, y: 55, size: 10, font, color: muted });
  summary.drawText("This report does not estimate overcharges or financial exposure.",
    { x: 40, y: 39, size: 10, font, color: muted });

  const sorted = [...leases].sort((a, b) => (a.property_name || "").localeCompare(b.property_name || ""));
  for (let offset = 0; offset < sorted.length; offset += 20) {
    const page = pdf.addPage([842, 595]);
    page.drawRectangle({ x: 0, y: 0, width: 842, height: 595, color: rgb(0.97, 0.98, 1) });
    page.drawText("Saved lease details", { x: 40, y: 548, size: 19, font: bold, color: ink });
    page.drawText("Property", { x: 40, y: 509, size: 10, font: bold, color: ink });
    page.drawText("Landlord", { x: 274, y: 509, size: 10, font: bold, color: ink });
    page.drawText("Type", { x: 440, y: 509, size: 10, font: bold, color: ink });
    page.drawText("Sq. ft.", { x: 560, y: 509, size: 10, font: bold, color: ink });
    page.drawText("Saved renewal", { x: 660, y: 509, size: 10, font: bold, color: ink });
    sorted.slice(offset, offset + 20).forEach((lease, index) => {
      const y = 481 - index * 21;
      if (index % 2 === 0) page.drawRectangle({ x: 36, y: y - 6, width: 770, height: 19, color: rgb(0.91, 0.94, 0.98) });
      page.drawText(fitted(lease.property_name || "Unnamed lease", 215, 9), { x: 40, y, size: 9, font, color: ink });
      page.drawText(fitted(lease.landlord || "-", 150, 9), { x: 274, y, size: 9, font, color: ink });
      page.drawText(fitted(lease.lease_type || "-", 105, 9), { x: 440, y, size: 9, font, color: ink });
      page.drawText(lease.square_feet == null ? "-" : String(lease.square_feet), { x: 560, y, size: 9, font, color: ink });
      page.drawText(lease.renewal_date || "Not saved", { x: 660, y, size: 9, font, color: ink });
    });
  }
  pdf.getPages().forEach((page, index) => {
    page.drawText(`SaveOnLease | Page ${index + 1} of ${pdf.getPageCount()}`,
      { x: 40, y: 18, size: 8, font, color: muted });
  });
  return pdf.save();
}

router.post("/portfolio-board-pdf", async (ctx) => {
  try {
    const body = await ctx.request.body({ type: "json" }).value as PortfolioRequest;

    if (body?.source === "saved_portfolio") {
      const token = ctx.request.headers.get("authorization")?.match(/^Bearer (\S+)$/i)?.[1];
      if (!token) {
        ctx.response.status = 401;
        ctx.response.body = { error: "Authentication required" };
        return;
      }
      const { data: { user }, error: authError } = await supabase.auth.getUser(token);
      if (authError || !user) {
        ctx.response.status = 401;
        ctx.response.body = { error: "Authentication required" };
        return;
      }
      const { data: leases, count, error: leaseError } = await supabase.from("portfolio_leases")
        .select("property_name,landlord,square_feet,lease_type,renewal_date", { count: "exact" })
        .eq("user_id", user.id).is("deleted_at", null)
        .order("property_name", { ascending: true });
      if (leaseError) {
        ctx.response.status = 500;
        ctx.response.body = { error: "Unable to load portfolio" };
        return;
      }
      if (!count) {
        ctx.response.status = 409;
        ctx.response.body = { error: "Add a lease before exporting a report" };
        return;
      }
      if (count > 1000) {
        ctx.response.status = 413;
        ctx.response.body = { error: "Portfolio is too large for one PDF export" };
        return;
      }
      const pdfBytes = await generateSavedPortfolioPdf(leases ?? []);
      ctx.response.status = 200;
      ctx.response.headers.set("Content-Type", "application/pdf");
      ctx.response.headers.set("Content-Disposition", "attachment; filename=portfolio_board_report.pdf");
      ctx.response.body = pdfBytes;
      return;
    }

    const {
      leases = [],
      totalExposure = 0,
      riskBuckets = { critical: 0, watch: 0, safe: 0 },
      companyName = "SaveOnLease Client",
      confidential = false,
      priorExposure = 0,
    } = body;

    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([842, 595]); // Landscape A4

    const { width, height } = page.getSize();

    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    // Dark executive background
    page.drawRectangle({
      x: 0,
      y: 0,
      width,
      height,
      color: rgb(0.06, 0.09, 0.16),
    });

    // Header
    page.drawText(companyName, {
      x: 40,
      y: height - 60,
      size: 22,
      font: boldFont,
      color: rgb(1, 1, 1),
    });

    page.drawText("Institutional Lease Risk Report", {
      x: 40,
      y: height - 85,
      size: 12,
      font,
      color: rgb(0.7, 0.8, 0.95),
    });

    // AI-driven portfolio risk scoring
    const totalLeases = leases.length || 1;

    const nowDate = new Date();

    // Exposure + time weighted scoring
    let weightedRisk = 0;
    let totalWeightedExposure = 0;

    leases.forEach(l => {
      const exposure = l.estimated_exposure ?? 0;
      if (!l.renewal_date) return;

      const renewal = new Date(l.renewal_date);
      const diffDays = Math.max(
        0,
        Math.floor((renewal.getTime() - nowDate.getTime()) / (1000*60*60*24))
      );

      const timeWeight = diffDays < 90 ? 1.5 : diffDays < 180 ? 1.1 : 0.7;
      weightedRisk += exposure * timeWeight;
      totalWeightedExposure += exposure;
    });

    const portfolioRiskScore = totalWeightedExposure === 0
      ? 0
      : Math.min(100, Math.round((weightedRisk / totalWeightedExposure) * 40));

    const riskLabel =
      portfolioRiskScore > 70
        ? "High Structural Risk"
        : portfolioRiskScore > 40
        ? "Moderate Risk"
        : "Stable";

    const criticalRatio = riskBuckets.critical / totalLeases;
    const watchRatio = riskBuckets.watch / totalLeases;

    const narrative = `As of ${new Date().toLocaleDateString()}, the portfolio includes ${leases.length} active leases with a modeled exposure of $${Number(totalExposure).toLocaleString()}. The AI risk score is ${portfolioRiskScore}/100, indicating ${riskLabel}. ${riskBuckets.critical} leases require immediate attention within 90 days.`;

    page.drawText(narrative, {
      x: 40,
      y: height - 120,
      size: 11,
      font,
      color: rgb(0.85, 0.9, 1),
      maxWidth: width - 80,
      lineHeight: 14,
    });

    // KPI section
    page.drawText(`Total Leases: ${leases.length}`, {
      x: 40,
      y: height - 170,
      size: 14,
      font: boldFont,
      color: rgb(1, 1, 1),
    });

    page.drawText(`Critical (<90 days): ${riskBuckets.critical}`, {
      x: 40,
      y: height - 195,
      size: 14,
      font,
      color: rgb(1, 0.4, 0.4),
    });

    page.drawText(`Total Exposure: $${Number(totalExposure).toLocaleString()}`, {
      x: 40,
      y: height - 220,
      size: 14,
      font,
      color: rgb(0.6, 0.9, 1),
    });

    // Portfolio mix heat bar
    const barWidth = 400;
    const barX = 40;
    const barY = height - 260;

    const criticalWidth = (riskBuckets.critical / totalLeases) * barWidth;
    const watchWidth = (riskBuckets.watch / totalLeases) * barWidth;
    const safeWidth = (riskBuckets.safe / totalLeases) * barWidth;

    page.drawRectangle({ x: barX, y: barY, width: criticalWidth, height: 14, color: rgb(1,0.4,0.4) });
    page.drawRectangle({ x: barX + criticalWidth, y: barY, width: watchWidth, height: 14, color: rgb(1,0.75,0.2) });
    page.drawRectangle({ x: barX + criticalWidth + watchWidth, y: barY, width: safeWidth, height: 14, color: rgb(0.4,0.8,0.4) });

    // Heat legend
    const legendY = height - 250;

    page.drawText("Risk Legend:", {
      x: width - 260,
      y: legendY,
      size: 10,
      font: boldFont,
      color: rgb(1,1,1),
    });

    page.drawRectangle({ x: width - 260, y: legendY - 20, width: 12, height: 12, color: rgb(1,0.4,0.4) });
    page.drawText(`Critical (${Math.round(criticalRatio*100)}%)`, { x: width - 240, y: legendY - 18, size: 9, font, color: rgb(1,1,1) });

    page.drawRectangle({ x: width - 260, y: legendY - 40, width: 12, height: 12, color: rgb(1,0.75,0.2) });
    page.drawText(`Watch (${Math.round(watchRatio*100)}%)`, { x: width - 240, y: legendY - 38, size: 9, font, color: rgb(1,1,1) });

    page.drawRectangle({ x: width - 260, y: legendY - 60, width: 12, height: 12, color: rgb(0.4,0.8,0.4) });
    page.drawText(`Safe (${Math.round((riskBuckets.safe/totalLeases)*100)}%)`, { x: width - 240, y: legendY - 58, size: 9, font, color: rgb(1,1,1) });

    // Exposure-weighted 12 month forecast
    const now = new Date();
    const monthlyExposure = Array(12).fill(0);

    leases.forEach((lease) => {
      if (!lease.renewal_date) return;

      const renewal = new Date(lease.renewal_date);
      const diffMonths =
        (renewal.getFullYear() - now.getFullYear()) * 12 +
        (renewal.getMonth() - now.getMonth());

      if (diffMonths >= 0 && diffMonths < 12) {
        monthlyExposure[diffMonths] += lease.estimated_exposure ?? 0;
      }
    });

    const maxExposure = Math.max(...monthlyExposure, 1);
    const chartBaseY = height - 360;

    page.drawText("12-Month Exposure Forecast", {
      x: 40,
      y: chartBaseY + 150,
      size: 12,
      font: boldFont,
      color: rgb(1, 1, 1),
    });

    monthlyExposure.forEach((value, i) => {
      const barHeight = (value / maxExposure) * 120;

      page.drawRectangle({
        x: 40 + i * 55,
        y: chartBaseY,
        width: 35,
        height: barHeight,
        color: rgb(0.4, 0.65, 1),
      });
    });

    /* -------------------------------------------------
       PAGE 2 — EXECUTIVE SUMMARY (CFO BRIEF)
    -------------------------------------------------- */

    const summaryPage = pdfDoc.addPage([842, 595]);
    const { width: sw, height: sh } = summaryPage.getSize();

    summaryPage.drawRectangle({ x:0, y:0, width:sw, height:sh, color: rgb(0.08,0.1,0.16) });

    summaryPage.drawText("Executive Portfolio Brief", {
      x: 40,
      y: sh - 60,
      size: 24,
      font: boldFont,
      color: rgb(1,1,1),
    });

    const bulletStartY = sh - 110;

    const bullets = [
      `• AI Risk Score: ${portfolioRiskScore}/100 (${riskLabel})`,
      `• Total Portfolio Exposure: $${Number(totalExposure).toLocaleString()}`,
      `• Critical Leases (<90 days): ${riskBuckets.critical}`,
      `• Exposure Concentration: ${Math.round(criticalRatio*100)}% high-risk` ,
    ];

    bullets.forEach((b, i) => {
      summaryPage.drawText(b, {
        x: 60,
        y: bulletStartY - (i * 30),
        size: 14,
        font,
        color: rgb(0.8,0.9,1),
      });
    });

    const modeledSpike = Math.round(totalExposure * 1.2);

    summaryPage.drawText(
      `• Modeled 20% Expense Increase Scenario: $${Number(modeledSpike).toLocaleString()}`,
      {
        x: 60,
        y: bulletStartY - (bullets.length * 30),
        size: 14,
        font,
        color: rgb(1,0.6,0.4),
      }
    );

    if (priorExposure > 0) {
      const delta = totalExposure - priorExposure;
      const direction = delta > 0 ? "increase" : "decrease";

      summaryPage.drawText(
        `• Trend vs Prior Report: ${direction} of $${Number(Math.abs(delta)).toLocaleString()}`,
        {
          x: 60,
          y: bulletStartY - ((bullets.length + 1) * 30),
          size: 14,
          font,
          color: delta > 0 ? rgb(1,0.4,0.4) : rgb(0.4,0.9,0.6),
        }
      );
    }

    /* -------------------------------------------------
       PAGE 2 — LEASE DETAIL TABLE (BOARD APPENDIX)
    -------------------------------------------------- */

    const detailPage = pdfDoc.addPage([842, 595]);
    const { width: dWidth, height: dHeight } = detailPage.getSize();

    // Light institutional background for appendix
    detailPage.drawRectangle({
      x: 0,
      y: 0,
      width: dWidth,
      height: dHeight,
      color: rgb(0.95, 0.97, 1),
    });

    detailPage.drawText(`${companyName} — Lease Detail Appendix`, {
      x: 40,
      y: dHeight - 50,
      size: 18,
      font: boldFont,
      color: rgb(0.1, 0.15, 0.3),
    });

    // Exposure subtotal by region
    const exposureByRegion: Record<string, number> = {};

    leases.forEach(l => {
      const region = l.region ?? "Unassigned";
      exposureByRegion[region] =
        (exposureByRegion[region] ?? 0) + (l.estimated_exposure ?? 0);
    });

    let regionY = dHeight - 70;
    detailPage.drawText("Exposure by Region:", {
      x: 40,
      y: regionY,
      size: 10,
      font: boldFont,
      color: rgb(0.1,0.15,0.3),
    });

    regionY -= 15;
    Object.entries(exposureByRegion).forEach(([region, value]) => {
      detailPage.drawText(
        `${region}: $${Number(value).toLocaleString()}`,
        {
          x: 40,
          y: regionY,
          size: 9,
          font,
          color: rgb(0.2,0.25,0.4),
        }
      );
      regionY -= 14;
    });

    let tableY = regionY - 20;

    // Table headers
    detailPage.drawText("Property", {
      x: 40,
      y: tableY,
      size: 10,
      font: boldFont,
      color: rgb(0.1, 0.15, 0.3),
    });

    detailPage.drawText("Lease Type", {
      x: 260,
      y: tableY,
      size: 10,
      font: boldFont,
      color: rgb(0.1, 0.15, 0.3),
    });

    detailPage.drawText("Renewal", {
      x: 380,
      y: tableY,
      size: 10,
      font: boldFont,
      color: rgb(0.1, 0.15, 0.3),
    });

    detailPage.drawText("Est. Exposure", {
      x: 480,
      y: tableY,
      size: 10,
      font: boldFont,
      color: rgb(0.1, 0.15, 0.3),
    });

    tableY -= 20;

    const sortedLeases = [...leases]
      .sort((a, b) => (b.estimated_exposure ?? 0) - (a.estimated_exposure ?? 0));

    let currentPage = detailPage;
    let currentY = tableY;

sortedLeases.forEach((lease) => {
      if (currentY < 60) {
        currentPage = pdfDoc.addPage([842, 595]);
        currentPage.drawRectangle({
          x: 0,
          y: 0,
          width: dWidth,
          height: dHeight,
          color: rgb(0.95,0.97,1),
        });
        currentY = dHeight - 60;
      }

      currentPage.drawText(lease.property_name ?? "—", {
        x: 40,
        y: currentY,
        size: 9,
        font,
        color: rgb(0.2,0.25,0.4),
      });

      currentPage.drawText(lease.lease_type ?? "—", {
        x: 260,
        y: currentY,
        size: 9,
        font,
        color: rgb(0.2,0.25,0.4),
      });

      currentPage.drawText(
        lease.renewal_date
          ? new Date(lease.renewal_date).toLocaleDateString()
          : "—",
        { x: 380, y: currentY, size: 9, font, color: rgb(0.2,0.25,0.4) }
      );

      currentPage.drawText(
        `$${Number(lease.estimated_exposure ?? 0).toLocaleString()}`,
        { x: 480, y: currentY, size: 9, font, color: rgb(0.1,0.2,0.5) }
      );

      currentY -= 18;
    });

    // Region breakout slides
    const regions = Object.keys(exposureByRegion);

    regions.forEach(regionName => {
      const regionLeases = leases.filter(l => (l.region ?? "Unassigned") === regionName);
      if (regionLeases.length === 0) return;

      const regionPage = pdfDoc.addPage([842, 595]);
      const { width: rw, height: rh } = regionPage.getSize();

      regionPage.drawRectangle({ x:0, y:0, width:rw, height:rh, color: rgb(0.1,0.12,0.18) });

      regionPage.drawText(`${regionName} — Regional Risk Overview`, {
        x: 40,
        y: rh - 60,
        size: 20,
        font: boldFont,
        color: rgb(1,1,1),
      });

      const regionExposure = exposureByRegion[regionName] ?? 0;

      regionPage.drawText(`Total Exposure: $${Number(regionExposure).toLocaleString()}`, {
        x: 40,
        y: rh - 100,
        size: 14,
        font,
        color: rgb(0.6,0.9,1),
      });

      regionPage.drawText(`Lease Count: ${regionLeases.length}`, {
        x: 40,
        y: rh - 125,
        size: 14,
        font,
        color: rgb(1,1,1),
      });
    });

    // Confidential watermark
    if (confidential) {
      page.drawText("CONFIDENTIAL", {
        x: width / 2 - 150,
        y: height / 2,
        size: 60,
        font: boldFont,
        color: rgb(1, 1, 1),
        opacity: 0.05,
      });
    }

    // Footer
    page.drawText(`Generated ${new Date().toLocaleString()}`, {
      x: 40,
      y: 30,
      size: 8,
      font,
      color: rgb(0.7, 0.8, 0.95),
    });

    const pages = pdfDoc.getPages();

    const distributionLink = `Investor Portal: https://saveonlease.com/investor-report/${Date.now()}`;

    pages.forEach((p, i) => {
      const { width: pw } = p.getSize();

      p.drawText(`Page ${i + 1} of ${pages.length}`, {
        x: pw - 120,
        y: 20,
        size: 8,
        font,
        color: rgb(0.6,0.7,0.9),
      });

      p.drawText(REPORT_VERSION, {
        x: 40,
        y: 20,
        size: 8,
        font,
        color: rgb(0.6,0.7,0.9),
      });
    });

    pages.forEach((p) => {
      p.drawText(distributionLink, {
        x: 40,
        y: 10,
        size: 8,
        font,
        color: rgb(0.5,0.6,0.8),
      });
    });

    const pdfBytes = await pdfDoc.save();

    ctx.response.status = 200;
    ctx.response.headers.set("Content-Type", "application/pdf");
    ctx.response.headers.set(
      "Content-Disposition",
      `attachment; filename="portfolio_board_report.pdf"`
    );
    ctx.response.body = pdfBytes;
  } catch (err) {
    console.error(err);
    ctx.response.status = 500;
    ctx.response.body = { error: "Failed to generate portfolio PDF" };
  }
});

export default router;
