import { Router } from "https://deno.land/x/oak@v12.6.1/mod.ts";
import { PDFDocument, StandardFonts, rgb } from "https://esm.sh/pdf-lib@1.17.1";

const REPORT_VERSION = "v1.3 | Generated by SaveOnLease Engine";

interface PortfolioLease {
  property_name?: string;
  lease_type?: string;
  renewal_date?: string;
  estimated_exposure?: number;
  diffDays?: number;
  region?: string;
}

interface PortfolioRequest {
  leases: PortfolioLease[];
  totalExposure: number;
  riskBuckets: {
    critical: number;
    watch: number;
    safe: number;
  };
  companyName: string;
  confidential: boolean;
  priorExposure?: number;
}

const router = new Router();

router.post("/portfolio-board-pdf", async (ctx) => {
  try {
    const body = await ctx.request.body({ type: "json" }).value as PortfolioRequest;

    const {
      leases = [],
      totalExposure = 0,
      riskBuckets = { critical: 0, watch: 0, safe: 0 },
      companyName = "SaveOnLease Client",
      confidential = false,
      priorExposure = 0,
    } = body;

    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([842, 595]); // Landscape A4

    const { width, height } = page.getSize();

    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    // Dark executive background
    page.drawRectangle({
      x: 0,
      y: 0,
      width,
      height,
      color: rgb(0.06, 0.09, 0.16),
    });

    // Header
    page.drawText(companyName, {
      x: 40,
      y: height - 60,
      size: 22,
      font: boldFont,
      color: rgb(1, 1, 1),
    });

    page.drawText("Institutional Lease Risk Report", {
      x: 40,
      y: height - 85,
      size: 12,
      font,
      color: rgb(0.7, 0.8, 0.95),
    });

    // AI-driven portfolio risk scoring
    const totalLeases = leases.length || 1;

    const nowDate = new Date();

    // Exposure + time weighted scoring
    let weightedRisk = 0;
    let totalWeightedExposure = 0;

    leases.forEach(l => {
      const exposure = l.estimated_exposure ?? 0;
      if (!l.renewal_date) return;

      const renewal = new Date(l.renewal_date);
      const diffDays = Math.max(
        0,
        Math.floor((renewal.getTime() - nowDate.getTime()) / (1000*60*60*24))
      );

      const timeWeight = diffDays < 90 ? 1.5 : diffDays < 180 ? 1.1 : 0.7;
      weightedRisk += exposure * timeWeight;
      totalWeightedExposure += exposure;
    });

    const portfolioRiskScore = totalWeightedExposure === 0
      ? 0
      : Math.min(100, Math.round((weightedRisk / totalWeightedExposure) * 40));

    const riskLabel =
      portfolioRiskScore > 70
        ? "High Structural Risk"
        : portfolioRiskScore > 40
        ? "Moderate Risk"
        : "Stable";

    const criticalRatio = riskBuckets.critical / totalLeases;
    const watchRatio = riskBuckets.watch / totalLeases;

    const narrative = `As of ${new Date().toLocaleDateString()}, the portfolio includes ${leases.length} active leases with a modeled exposure of $${Number(totalExposure).toLocaleString()}. The AI risk score is ${portfolioRiskScore}/100, indicating ${riskLabel}. ${riskBuckets.critical} leases require immediate attention within 90 days.`;

    page.drawText(narrative, {
      x: 40,
      y: height - 120,
      size: 11,
      font,
      color: rgb(0.85, 0.9, 1),
      maxWidth: width - 80,
      lineHeight: 14,
    });

    // KPI section
    page.drawText(`Total Leases: ${leases.length}`, {
      x: 40,
      y: height - 170,
      size: 14,
      font: boldFont,
      color: rgb(1, 1, 1),
    });

    page.drawText(`Critical (<90 days): ${riskBuckets.critical}`, {
      x: 40,
      y: height - 195,
      size: 14,
      font,
      color: rgb(1, 0.4, 0.4),
    });

    page.drawText(`Total Exposure: $${Number(totalExposure).toLocaleString()}`, {
      x: 40,
      y: height - 220,
      size: 14,
      font,
      color: rgb(0.6, 0.9, 1),
    });

    // Portfolio mix heat bar
    const barWidth = 400;
    const barX = 40;
    const barY = height - 260;

    const criticalWidth = (riskBuckets.critical / totalLeases) * barWidth;
    const watchWidth = (riskBuckets.watch / totalLeases) * barWidth;
    const safeWidth = (riskBuckets.safe / totalLeases) * barWidth;

    page.drawRectangle({ x: barX, y: barY, width: criticalWidth, height: 14, color: rgb(1,0.4,0.4) });
    page.drawRectangle({ x: barX + criticalWidth, y: barY, width: watchWidth, height: 14, color: rgb(1,0.75,0.2) });
    page.drawRectangle({ x: barX + criticalWidth + watchWidth, y: barY, width: safeWidth, height: 14, color: rgb(0.4,0.8,0.4) });

    // Heat legend
    const legendY = height - 250;

    page.drawText("Risk Legend:", {
      x: width - 260,
      y: legendY,
      size: 10,
      font: boldFont,
      color: rgb(1,1,1),
    });

    page.drawRectangle({ x: width - 260, y: legendY - 20, width: 12, height: 12, color: rgb(1,0.4,0.4) });
    page.drawText(`Critical (${Math.round(criticalRatio*100)}%)`, { x: width - 240, y: legendY - 18, size: 9, font, color: rgb(1,1,1) });

    page.drawRectangle({ x: width - 260, y: legendY - 40, width: 12, height: 12, color: rgb(1,0.75,0.2) });
    page.drawText(`Watch (${Math.round(watchRatio*100)}%)`, { x: width - 240, y: legendY - 38, size: 9, font, color: rgb(1,1,1) });

    page.drawRectangle({ x: width - 260, y: legendY - 60, width: 12, height: 12, color: rgb(0.4,0.8,0.4) });
    page.drawText(`Safe (${Math.round((riskBuckets.safe/totalLeases)*100)}%)`, { x: width - 240, y: legendY - 58, size: 9, font, color: rgb(1,1,1) });

    // Exposure-weighted 12 month forecast
    const now = new Date();
    const monthlyExposure = Array(12).fill(0);

    leases.forEach((lease) => {
      if (!lease.renewal_date) return;

      const renewal = new Date(lease.renewal_date);
      const diffMonths =
        (renewal.getFullYear() - now.getFullYear()) * 12 +
        (renewal.getMonth() - now.getMonth());

      if (diffMonths >= 0 && diffMonths < 12) {
        monthlyExposure[diffMonths] += lease.estimated_exposure ?? 0;
      }
    });

    const maxExposure = Math.max(...monthlyExposure, 1);
    const chartBaseY = height - 360;

    page.drawText("12-Month Exposure Forecast", {
      x: 40,
      y: chartBaseY + 150,
      size: 12,
      font: boldFont,
      color: rgb(1, 1, 1),
    });

    monthlyExposure.forEach((value, i) => {
      const barHeight = (value / maxExposure) * 120;

      page.drawRectangle({
        x: 40 + i * 55,
        y: chartBaseY,
        width: 35,
        height: barHeight,
        color: rgb(0.4, 0.65, 1),
      });
    });

    /* -------------------------------------------------
       PAGE 2 — EXECUTIVE SUMMARY (CFO BRIEF)
    -------------------------------------------------- */

    const summaryPage = pdfDoc.addPage([842, 595]);
    const { width: sw, height: sh } = summaryPage.getSize();

    summaryPage.drawRectangle({ x:0, y:0, width:sw, height:sh, color: rgb(0.08,0.1,0.16) });

    summaryPage.drawText("Executive Portfolio Brief", {
      x: 40,
      y: sh - 60,
      size: 24,
      font: boldFont,
      color: rgb(1,1,1),
    });

    const bulletStartY = sh - 110;

    const bullets = [
      `• AI Risk Score: ${portfolioRiskScore}/100 (${riskLabel})`,
      `• Total Portfolio Exposure: $${Number(totalExposure).toLocaleString()}`,
      `• Critical Leases (<90 days): ${riskBuckets.critical}`,
      `• Exposure Concentration: ${Math.round(criticalRatio*100)}% high-risk` ,
    ];

    bullets.forEach((b, i) => {
      summaryPage.drawText(b, {
        x: 60,
        y: bulletStartY - (i * 30),
        size: 14,
        font,
        color: rgb(0.8,0.9,1),
      });
    });

    const modeledSpike = Math.round(totalExposure * 1.2);

    summaryPage.drawText(
      `• Modeled 20% Expense Increase Scenario: $${Number(modeledSpike).toLocaleString()}`,
      {
        x: 60,
        y: bulletStartY - (bullets.length * 30),
        size: 14,
        font,
        color: rgb(1,0.6,0.4),
      }
    );

    if (priorExposure > 0) {
      const delta = totalExposure - priorExposure;
      const direction = delta > 0 ? "increase" : "decrease";

      summaryPage.drawText(
        `• Trend vs Prior Report: ${direction} of $${Number(Math.abs(delta)).toLocaleString()}`,
        {
          x: 60,
          y: bulletStartY - ((bullets.length + 1) * 30),
          size: 14,
          font,
          color: delta > 0 ? rgb(1,0.4,0.4) : rgb(0.4,0.9,0.6),
        }
      );
    }

    /* -------------------------------------------------
       PAGE 2 — LEASE DETAIL TABLE (BOARD APPENDIX)
    -------------------------------------------------- */

    const detailPage = pdfDoc.addPage([842, 595]);
    const { width: dWidth, height: dHeight } = detailPage.getSize();

    // Light institutional background for appendix
    detailPage.drawRectangle({
      x: 0,
      y: 0,
      width: dWidth,
      height: dHeight,
      color: rgb(0.95, 0.97, 1),
    });

    detailPage.drawText(`${companyName} — Lease Detail Appendix`, {
      x: 40,
      y: dHeight - 50,
      size: 18,
      font: boldFont,
      color: rgb(0.1, 0.15, 0.3),
    });

    // Exposure subtotal by region
    const exposureByRegion: Record<string, number> = {};

    leases.forEach(l => {
      const region = l.region ?? "Unassigned";
      exposureByRegion[region] =
        (exposureByRegion[region] ?? 0) + (l.estimated_exposure ?? 0);
    });

    let regionY = dHeight - 70;
    detailPage.drawText("Exposure by Region:", {
      x: 40,
      y: regionY,
      size: 10,
      font: boldFont,
      color: rgb(0.1,0.15,0.3),
    });

    regionY -= 15;
    Object.entries(exposureByRegion).forEach(([region, value]) => {
      detailPage.drawText(
        `${region}: $${Number(value).toLocaleString()}`,
        {
          x: 40,
          y: regionY,
          size: 9,
          font,
          color: rgb(0.2,0.25,0.4),
        }
      );
      regionY -= 14;
    });

    let tableY = regionY - 20;

    // Table headers
    detailPage.drawText("Property", {
      x: 40,
      y: tableY,
      size: 10,
      font: boldFont,
      color: rgb(0.1, 0.15, 0.3),
    });

    detailPage.drawText("Lease Type", {
      x: 260,
      y: tableY,
      size: 10,
      font: boldFont,
      color: rgb(0.1, 0.15, 0.3),
    });

    detailPage.drawText("Renewal", {
      x: 380,
      y: tableY,
      size: 10,
      font: boldFont,
      color: rgb(0.1, 0.15, 0.3),
    });

    detailPage.drawText("Est. Exposure", {
      x: 480,
      y: tableY,
      size: 10,
      font: boldFont,
      color: rgb(0.1, 0.15, 0.3),
    });

    tableY -= 20;

    const sortedLeases = [...leases]
      .sort((a, b) => (b.estimated_exposure ?? 0) - (a.estimated_exposure ?? 0));

    let currentPage = detailPage;
    let currentY = tableY;

sortedLeases.forEach((lease) => {
      if (currentY < 60) {
        currentPage = pdfDoc.addPage([842, 595]);
        currentPage.drawRectangle({
          x: 0,
          y: 0,
          width: dWidth,
          height: dHeight,
          color: rgb(0.95,0.97,1),
        });
        currentY = dHeight - 60;
      }

      currentPage.drawText(lease.property_name ?? "—", {
        x: 40,
        y: currentY,
        size: 9,
        font,
        color: rgb(0.2,0.25,0.4),
      });

      currentPage.drawText(lease.lease_type ?? "—", {
        x: 260,
        y: currentY,
        size: 9,
        font,
        color: rgb(0.2,0.25,0.4),
      });

      currentPage.drawText(
        lease.renewal_date
          ? new Date(lease.renewal_date).toLocaleDateString()
          : "—",
        { x: 380, y: currentY, size: 9, font, color: rgb(0.2,0.25,0.4) }
      );

      currentPage.drawText(
        `$${Number(lease.estimated_exposure ?? 0).toLocaleString()}`,
        { x: 480, y: currentY, size: 9, font, color: rgb(0.1,0.2,0.5) }
      );

      currentY -= 18;
    });

    // Region breakout slides
    const regions = Object.keys(exposureByRegion);

    regions.forEach(regionName => {
      const regionLeases = leases.filter(l => (l.region ?? "Unassigned") === regionName);
      if (regionLeases.length === 0) return;

      const regionPage = pdfDoc.addPage([842, 595]);
      const { width: rw, height: rh } = regionPage.getSize();

      regionPage.drawRectangle({ x:0, y:0, width:rw, height:rh, color: rgb(0.1,0.12,0.18) });

      regionPage.drawText(`${regionName} — Regional Risk Overview`, {
        x: 40,
        y: rh - 60,
        size: 20,
        font: boldFont,
        color: rgb(1,1,1),
      });

      const regionExposure = exposureByRegion[regionName] ?? 0;

      regionPage.drawText(`Total Exposure: $${Number(regionExposure).toLocaleString()}`, {
        x: 40,
        y: rh - 100,
        size: 14,
        font,
        color: rgb(0.6,0.9,1),
      });

      regionPage.drawText(`Lease Count: ${regionLeases.length}`, {
        x: 40,
        y: rh - 125,
        size: 14,
        font,
        color: rgb(1,1,1),
      });
    });

    // Confidential watermark
    if (confidential) {
      page.drawText("CONFIDENTIAL", {
        x: width / 2 - 150,
        y: height / 2,
        size: 60,
        font: boldFont,
        color: rgb(1, 1, 1),
        opacity: 0.05,
      });
    }

    // Footer
    page.drawText(`Generated ${new Date().toLocaleString()}`, {
      x: 40,
      y: 30,
      size: 8,
      font,
      color: rgb(0.7, 0.8, 0.95),
    });

    const pages = pdfDoc.getPages();

    const distributionLink = `Investor Portal: https://saveonlease.com/investor-report/${Date.now()}`;

    pages.forEach((p, i) => {
      const { width: pw } = p.getSize();

      p.drawText(`Page ${i + 1} of ${pages.length}`, {
        x: pw - 120,
        y: 20,
        size: 8,
        font,
        color: rgb(0.6,0.7,0.9),
      });

      p.drawText(REPORT_VERSION, {
        x: 40,
        y: 20,
        size: 8,
        font,
        color: rgb(0.6,0.7,0.9),
      });
    });

    pages.forEach((p) => {
      p.drawText(distributionLink, {
        x: 40,
        y: 10,
        size: 8,
        font,
        color: rgb(0.5,0.6,0.8),
      });
    });

    const pdfBytes = await pdfDoc.save();

    ctx.response.status = 200;
    ctx.response.headers.set("Content-Type", "application/pdf");
    ctx.response.headers.set(
      "Content-Disposition",
      `attachment; filename="portfolio_board_report.pdf"`
    );
    ctx.response.body = pdfBytes;
  } catch (err) {
    console.error(err);
    ctx.response.status = 500;
    ctx.response.body = { error: "Failed to generate portfolio PDF" };
  }
});

export default router;