FROM denoland/deno:1.41.1

WORKDIR /app

# Cache dependencies first
COPY deno.json deno.lock ./
RUN deno cache deno.json

# Copy the rest of the worker
COPY . .

EXPOSE 8000

CMD ["run", "--allow-net", "--allow-read", "--allow-env", "main.ts"]
