FROM denoland/deno:2.5.6

WORKDIR /app

# Cache dependencies first
COPY deno.json deno.lock ./
RUN deno cache deno.json

# Copy the rest of the worker
COPY . .

EXPOSE 8000

CMD ["deno","run","--allow-net","--allow-env","--allow-read","--allow-write=/tmp","main.ts"]


